### ISSUE TITLE
AWS policy attachment failure 

### ISSUE THREAD

**Issue by sherylanngayle** [mapbox/asset-tracking#10]
The stack fails to deploy because of the error below. AWSLambdaFullAccess IAM policy was deprecated as of March 1, 2021 so the solution needs to be updated with a different policy.

AWS Policy deprecation: https://docs.aws.amazon.com/lambda/latest/dg/access-control-identity-based.html

  aws:iam:RolePolicyAttachment (mapboxQuery4c238266-32be53a2):
    error: Error attaching policy arn:aws:iam::aws:policy/AWSLambdaFullAccess to IAM Role mapboxQuery4c238266-29ca2bb: NoSuchEntity: Policy arn:aws:iam::aws:policy/AWSLambdaFullAccess does not exist or is not attachable.
    	status code: 404, request id: 50cf0869-c0d9-4d96-9bbd-4fc45c0a5c22

**Comment by ryanbaumann** [comment]
cc/ @cmtoomey

**Comment by Spottybadrabbit** [comment]
@ryanbaumann @sherylanngayle any updates with this error?

```
     Type                                   Name                          Status                  Info
     pulumi:pulumi:Stack                    assettracking-testing         **failed**              1 error
 +   ├─ aws:iam:RolePolicy                  iotRolePolicy                 created
 +   ├─ aws:iam:RolePolicy                  firehoserolepolicy            created
 +   ├─ aws:kinesis:FirehoseDeliveryStream  assetFirehose                 created
 +   ├─ aws:iot:TopicRule                   iotAssetIngest                created
     └─ aws:apigateway:x:API                mapboxQuery
 +      ├─ aws:iam:RolePolicyAttachment     mapboxQuery4c238266-32be53a2  **creating failed**     1 error
 +      └─ aws:lambda:Function              mapboxQuery4c238266           created

Diagnostics:
  aws:iam:RolePolicyAttachment (mapboxQuery4c238266-32be53a2):
    error: Error attaching policy arn:aws:iam::aws:policy/AWSLambdaFullAccess to IAM Role mapboxQuery4c238266-6662fab: NoSuchEntity: Policy arn:aws:iam::aws:policy/AWSLambdaFullAccess does not exist or is not attachable.
    	status code: 404, request id: 847abba1-0384-490d-94e1-957d8f312a08

  pulumi:pulumi:Stack (assettracking-testing):
    error: update failed
```

I got the same one

**Comment by cmtoomey** [comment]
This has been fixed via a dependency update. 

Please be sure to pull and install latest dependencies, and upgrade your Pulumi CLI.
