### ISSUE TITLE
error: aws:lambda/function:Function resource 'mapboxStreamProcessor' has a problem

### ISSUE THREAD

**Issue by romanallosense** [mapbox/asset-tracking#4]
When running the instructions on my Mac Pro with "pulumi up", the following error prompts:

Diagnostics:
  aws:lambda:Function (mapboxStreamProcessor):
    error: aws:lambda/function:Function resource 'mapboxStreamProcessor' has a problem: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 go1.x java8 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x provided python2.7 python3.6 python3.7 ruby2.5], got nodejs12.x

**Comment by romanallosense** [comment]
Found the solution, to the problem.

There was a dependency issue with Pulumi using the AWS Terraform Provider (https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/lambda/).

To resolve, I installed @pulumi/aws (https://github.com/pulumi/pulumi-aws) on my Mac:
**npm install @pulumi/aws**

**Comment by cmtoomey** [comment]
This is due to the pulumi dependencies being out of date in `package-lock.json`. I will bump and re-commit.

**Comment by cmtoomey** [comment]
I believe the updated `master` branch and/or an update to pulumi CLI should resolve this issue. Please re-open if you continue to experience it.
