### ISSUE TITLE
error: Error creating Lambda function: InvalidParameterValueException: The runtime parameter of nodejs8.10 is no longer supported

### ISSUE THREAD

**Issue by amoschong** [mapbox/asset-tracking#7]
$ pulumi up failed to create the mapboxQuery Lambda function due to deprecated Node.js version.  I am walking through the instructions in RHEL.  

error: Error creating Lambda function: InvalidParameterValueException: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.

It'd also appear the latest version of @types/aws-lambda is 8.10.51 - still nodejs8.x I supposed - from looking it up in npmjs.com.

**Comment by cmtoomey** [comment]
Thanks for the issue @amoschong. There is a PR in flight and we'll get this resolved this week.

**Comment by cmtoomey** [comment]
This should be resolved now @amoschong - Dependencies have been updated and runtimes all reflect Node12.

Let me know if you continue to have issues.
