### ISSUE TITLE
Error on mapboxStreamProcessor Lambda

### ISSUE THREAD

**Issue by matansagee** [mapbox/asset-tracking#8]
The lambda is failing on 
`{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@pulumi/aws/iot/index.js'\nRequire stack:\n- /var/task/__index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@pulumi/aws/iot/index.js'",
        "Require stack:",
        "- /var/task/__index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1133:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)",
        "    at Module.load (internal/modules/cjs/loader.js:977:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:877:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)",
        "    at internal/main/run_main_module.js:18:47"
    ]
}`

**Comment by cmtoomey** [comment]
@matansagee - is this when running the pipeline or during deploy.

**Comment by amoschong** [comment]
I am running into the exact same error when the function tries to execute.

**Comment by matansagee** [comment]
@cmoloney it happens when I'm running the pipeline

**Comment by cmtoomey** [comment]
@matansagee @amoschong - I found the source of the problem and have pushed a PR.

All existing functionality in `master` has been preserved - should be good-to-go.
